### ISSUE TITLE
fail to evaluate array with gaps

### ISSUE THREAD

**Issue by nofun97** [arr-ai/arrai#195]
### Description
It fails to evaluate this
```
{ |@, @item| (0, 1), (2, 3) }
```

It is an array with a gap as there is no item at index one, but internally it still thinks that it's an array and fails to evaluate it.

### Steps to Reproduce
1. `arrai eval '{ |@, @item| (0, 1), (2, 3) }'`

**Expected behavior:**
Evaluates to
```
{ (@: 0, @item: 1), (@:2, @item: 3)}
```

**Actual behavior:**
```
panic: Repr(): unexpected Value type <nil>: <nil>

goroutine 1 [running]:
github.com/arr-ai/arrai/rel.reprValue(0x0, 0x0, 0x49052e0, 0xc000491540)
	/Users/allanadn/work/github.com/arr-ai/arrai/rel/value_repr.go:162 +0x6b1
github.com/arr-ai/arrai/rel.reprArray(0xc000695400, 0x3, 0x4, 0x0, 0x49052e0, 0xc000491540)
	/Users/allanadn/work/github.com/arr-ai/arrai/rel/value_repr.go:79 +0x120
github.com/arr-ai/arrai/rel.reprValue(0x491cfc0, 0xc0004914a0, 0x49052e0, 0xc000491540)
	/Users/allanadn/work/github.com/arr-ai/arrai/rel/value_repr.go:146 +0x65e
github.com/arr-ai/arrai/rel.Repr(...)
	/Users/allanadn/work/github.com/arr-ai/arrai/rel/value_repr.go:168
main.evalExpr(0x47f8545, 0x1, 0x7ffeefbff7d4, 0x1e, 0x49051a0, 0xc0001aa008, 0x0, 0xc0003f7d90)
	/Users/allanadn/work/github.com/arr-ai/arrai/cmd/arrai/eval.go:39 +0x38f
main.evalImpl(...)
	/Users/allanadn/work/github.com/arr-ai/arrai/cmd/arrai/eval.go:22
main.eval(0xc000533b80, 0x1, 0x1)
	/Users/allanadn/work/github.com/arr-ai/arrai/cmd/arrai/eval.go:56 +0xab
github.com/urfave/cli/v2.(*Command).Run(0x4def880, 0xc000533ac0, 0x0, 0x0)
	/Users/allanadn/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/command.go:161 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc000392900, 0x4915c60, 0xc0001ae008, 0xc000194180, 0x3, 0x3, 0x0, 0x0)
	/Users/allanadn/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:302 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/allanadn/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
	/Users/allanadn/work/github.com/arr-ai/arrai/cmd/arrai/main.go:43 +0x115
exit status 2
```

### Your Environments
```sh
$ go version
go version go1.14 darwin/amd64
```

**Comment by marcelocantos** [comment]
In my original design, sequences with gaps would simply be `genericSet` but then you have to perform expensive analyses every time you manipulate the set. e.g.:

```arrai
let arrayWithHole = {|@, @item| (0, 1), (1, 2), (2, 4), (3, 8), (5, 32), (6, 64), (7, 128)};
arrayWithHole with (@: 4, @item: 16)
```

The result should be an Array, but it’s an O(_n_) operation to detect this. You could store metadata structures tracking what you have and whether it’s time to collapse to a specialised type, but you won’t get far down that path before ending up with the following concept.

A `UnionSet` holds one each of `Array`, `String`, `Bytes`, `Dict`, `IntSet` and `GenericSet`. When a tuple is introduced, it is added to exactly one of these, based on its own type. `ArrayItemTuple` goes into `Array`, `StringCharTuple` goes into `String`, etc. After a filter or removal, if only one of the subsets is non-empty, the result is that subset rather than the `UnionSet` (`None` if all are empty).

**Comment by marcelocantos** [comment]
A quick and dirty implementation of `Array` would be to simply mirror the implementation of `Dict`. You lose the benefits of a contiguous slice, but that's probably a small price to pay for the ease of implementation.
