### ISSUE TITLE
Error piping from arrai json to arrai x

### ISSUE THREAD

**Issue by orlade** [arr-ai/arrai#302]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Description

The example snippets includes transforming a stream via `arrai json`, but it doesn't work. Not clear whether it should. `arrai jx` works.

### Steps to Reproduce
1. `$ echo '{"a": "hello", "b": "world"}'| arrai json | arrai x '."a"'`

**Expected behavior:**

`"hello"`

**Actual behavior:**

Crash

* Debug&Crash Output

```
oliver@DELLBOX:~/dev/arrai$  echo '{"a": "hello", "b": "world"}' | arrai json | arrai x '."a"'
panic: unfinished

goroutine 1 [running]:
main.transform(0xc0003fc680, 0x1, 0x1)
        /home/oliver/dev/arrai/cmd/arrai/transform.go:15 +0x39
github.com/urfave/cli/v2.(*Command).Run(0x1207560, 0xc0003fc5c0, 0x0, 0x0)
        /home/oliver/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/urfave/cli/v2@v2.1.1/command.go:161 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc000001c80, 0xd245e0, 0xc000038080, 0xc000032180, 0x3, 0x3, 0x0, 0x0)
        /home/oliver/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:302 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
        /home/oliver/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
        /home/oliver/dev/arrai/cmd/arrai/main.go:78 +0x133
```

### Your Environments
```sh
$ go version
go version go1.14 linux/amd64

```

**Comment by marcelocantos** [comment]
The transform|x command doesn't work at present. #310

**Comment by marcelocantos** [comment]
#311 makes the bug less confusing.
